### ISSUE TITLE
Suggestion: Setup AppVeyor to build NMM

### ISSUE THREAD

**Issue by squid-box** [Nexus-Mods/Nexus-Mod-Manager#430]
So GitHub has some suggestions under the "Checks" tab on Pull Requests, and it seems like [AppVeyor](https://github.com/marketplace/appveyor) would be able to build NMM just fine (supports VS 2013/2015/2017, and has support for building Inno Setup installers).

Not saying we have to build the installer there, but it's usually good to at least verify a Pull Request compiles. Maybe one day someone even adds a unit test? 😆 

It's free for OpenSource projects.

**Comment by squid-box** [comment]
An example *appveyor.yml* from my branch:
```
version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build:
  project: NexusClient.sln
  verbosity: minimal
after_build:
- ps: "$workingDirectory = [System.Environment]::ExpandEnvironmentVariables(\"%APPVEYOR_BUILD_FOLDER%\") \nStart-Process -FilePath \"C:\\Program Files (x86)\\Inno Setup 5\\Compil32.exe\" -ArgumentList (\"/cc `\"Setup\\setup.iss`\"\") -WorkingDirectory $workingDirectory -Wait"
test: off
artifacts:
- path: Setup\bin\*.exe
```

Note that *setup.iss* would need to set *SignedUninstaller* to false.
